projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://eu1.prisma.sh/stefan-lachmann-e05219/my-web-stefan/
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml